/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 island.gltf --transform
Author: borsh_and (https://sketchfab.com/borsh_and)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-mangrove-greenhouse-4ad533f838f44fa583683ab7939c6aa1
Title: Stylized Mangrove Greenhouse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/island-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.94}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 66.04, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube001_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, 76.81, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube002_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube002_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, 66.04, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube003_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube003_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, 76.81, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube037_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube037_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, 66.04, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube004_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube004_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, 66.04, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100}>
            <mesh geometry={nodes.Cube007_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube007_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-3.12, 142.26, 2.25]} rotation={[-Math.PI / 2, 0, 0]} scale={86.82}>
            <mesh geometry={nodes.Cube006_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Cube006_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-3.12, 142.26, 2.25]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={86.82}>
            <mesh geometry={nodes.Cube008_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Cube008_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[578.29, 100, 161.02]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube005_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube005_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, 0, -327.77]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Circle_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Circle_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[126.64, 103.56, 810.94]} rotation={[-Math.PI / 2, 0, 0]} scale={106.97}>
            <mesh geometry={nodes.Circle010_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle010_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[51.19, 106.22, 783.59]} rotation={[-Math.PI / 2, 0, 2.88]} scale={24.3}>
            <mesh geometry={nodes.Plane008_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane008_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[0, 2.71, 46]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube028_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube028_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-182.63, 106.84, -414.13]} rotation={[3.11, 0.75, 1.43]} scale={100}>
            <mesh geometry={nodes.BezierCurve_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.BezierCurve_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[177.13, 51.09, -276.19]} rotation={[-Math.PI / 2, 0, 0]} scale={55.94}>
            <mesh geometry={nodes.Circle031_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle031_Line_art_Green__0.geometry} material={materials.Line_art_Green} />
          </group>
          <group position={[-43.38, 51.73, -487.26]} rotation={[-Math.PI / 2, 0, -0.92]} scale={73.07}>
            <mesh geometry={nodes.Circle032_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle032_Line_art_Green__0.geometry} material={materials.Line_art_Green} />
          </group>
          <group position={[20.42, -0.7, 392.58]} rotation={[-Math.PI / 2, 0, 0]} scale={[24.84, 24.84, 34.69]}>
            <mesh geometry={nodes.Circle033_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle033_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
            <mesh geometry={nodes.Circle034_Material003_0.geometry} material={materials['Material.003']} position={[-0.21, 0.21, 6.04]} rotation={[-0.5, -0.29, 0.47]} scale={[0.49, 0.45, 0.55]} />
            <mesh geometry={nodes.Circle035_Material003_0.geometry} material={materials['Material.003']} position={[-0.32, 0.24, 6.08]} rotation={[-0.01, 0.5, -1.32]} scale={[0.53, 0.5, 0.58]} />
            <mesh geometry={nodes.Circle036_Material003_0.geometry} material={materials['Material.003']} position={[-0.32, 0.24, 6.13]} rotation={[0.67, 0.03, -3.04]} scale={[0.52, 0.47, 0.61]} />
            <mesh geometry={nodes.Circle037_Material003_0.geometry} material={materials['Material.003']} position={[-0.21, 0.21, 5.97]} rotation={[-0.73, 0.19, -0.13]} scale={[0.39, 0.34, 0.47]} />
            <mesh geometry={nodes.Circle038_Material003_0.geometry} material={materials['Material.003']} position={[-0.21, 0.21, 6.06]} rotation={[0.61, -0.73, 2.46]} scale={[0.39, 0.32, 0.5]} />
            <mesh geometry={nodes.Circle039_Material003_0.geometry} material={materials['Material.003']} position={[-0.32, 0.24, 6.15]} rotation={[0.15, 0.32, -2.2]} scale={[0.47, 0.46, 0.5]} />
            <mesh geometry={nodes.Circle040_Material003_0.geometry} material={materials['Material.003']} position={[-0.19, 0.25, 6.19]} rotation={[0.21, -0.35, 1.75]} scale={[0.52, 0.51, 0.56]} />
            <mesh geometry={nodes.Circle041_Material003_0.geometry} material={materials['Material.003']} position={[-0.19, 0.25, 6.19]} rotation={[-0.36, 0.17, -0.46]} scale={[0.45, 0.43, 0.47]} />
          </group>
          <group position={[-100.53, -3.18, 333.74]} rotation={[-Math.PI / 2, 0, 0]} scale={[42.91, 42.91, 59.93]}>
            <mesh geometry={nodes.Circle042_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle042_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
            <mesh geometry={nodes.Circle043_Material003_0.geometry} material={materials['Material.003']} position={[-0.21, 0.21, 6.04]} rotation={[-0.5, -0.29, 0.47]} scale={[0.49, 0.45, 0.55]} />
            <mesh geometry={nodes.Circle044_Material003_0.geometry} material={materials['Material.003']} position={[-0.32, 0.24, 6.08]} rotation={[-0.01, 0.5, -1.32]} scale={[0.53, 0.5, 0.58]} />
            <mesh geometry={nodes.Circle045_Material003_0.geometry} material={materials['Material.003']} position={[-0.32, 0.24, 6.13]} rotation={[0.67, 0.03, -3.04]} scale={[0.52, 0.47, 0.61]} />
            <mesh geometry={nodes.Circle046_Material003_0.geometry} material={materials['Material.003']} position={[-0.21, 0.21, 5.97]} rotation={[-0.73, 0.19, -0.13]} scale={[0.39, 0.34, 0.47]} />
            <mesh geometry={nodes.Circle047_Material003_0.geometry} material={materials['Material.003']} position={[-0.21, 0.21, 6.06]} rotation={[0.61, -0.73, 2.46]} scale={[0.39, 0.32, 0.5]} />
            <mesh geometry={nodes.Circle048_Material003_0.geometry} material={materials['Material.003']} position={[-0.32, 0.24, 6.15]} rotation={[0.15, 0.32, -2.2]} scale={[0.47, 0.46, 0.5]} />
            <mesh geometry={nodes.Circle049_Material003_0.geometry} material={materials['Material.003']} position={[-0.19, 0.25, 6.19]} rotation={[0.21, -0.35, 1.75]} scale={[0.52, 0.51, 0.56]} />
            <mesh geometry={nodes.Circle050_Material003_0.geometry} material={materials['Material.003']} position={[-0.19, 0.25, 6.19]} rotation={[-0.36, 0.17, -0.46]} scale={[0.45, 0.43, 0.47]} />
          </group>
          <group position={[38.68, 260.72, 695.18]} rotation={[-Math.PI / 2, 0, 0]} scale={136}>
            <mesh geometry={nodes.Circle051_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle051_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[384.09, 232.67, 377.54]} rotation={[-Math.PI / 2, 0, 1.11]} scale={136}>
            <mesh geometry={nodes.Circle052_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle052_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-338.18, 260.72, 558.65]} rotation={[-Math.PI / 2, 0, 1.34]} scale={136}>
            <mesh geometry={nodes.Circle053_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle053_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[136.27, 246.8, -693.62]} rotation={[-Math.PI / 2, 0, 0]} scale={136}>
            <mesh geometry={nodes.Circle054_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle054_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[107.43, -0.76, 301.01]} rotation={[-Math.PI / 2, 0, 0]} scale={9.63}>
            <mesh geometry={nodes.Circle061_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle055_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[-0.09, -0.51, -1.7]} scale={[1.15, 1.15, 1.61]} />
            <mesh geometry={nodes.Circle056_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[-0.42, -0.06, -3]} scale={[1.15, 1.15, 1.61]} />
            <mesh geometry={nodes.Circle057_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[0.3, 0.29, 0.86]} scale={[1.15, 1.15, 1.61]} />
            <mesh geometry={nodes.Circle058_Material004_0.geometry} material={materials['Material.004']} position={[-0.42, 0.11, 0.35]} rotation={[-0.22, 0.35, 2.15]} scale={[0.92, 0.92, 1.29]} />
            <mesh geometry={nodes.Circle059_Material004_0.geometry} material={materials['Material.004']} position={[-0.64, 0.44, 0.35]} rotation={[0.58, -0.05, -0.07]} scale={[0.92, 0.92, 1.29]} />
            <mesh geometry={nodes.Circle060_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[0.37, -0.24, -0.68]} scale={[1.04, 1.04, 1.46]} />
            <mesh geometry={nodes.Circle062_Material004_0.geometry} material={materials['Material.004']} position={[-0.24, -0.96, 1.39]} rotation={[-0.53, -0.43, -2.51]} scale={[0.73, 0.73, 1.03]} />
          </group>
          <group position={[-118.72, -0.76, 476.35]} rotation={[-Math.PI / 2, 0, -0.84]} scale={12.57}>
            <mesh geometry={nodes.Circle069_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle063_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[-0.09, -0.51, -1.7]} scale={[1.15, 1.15, 1.61]} />
            <mesh geometry={nodes.Circle064_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[-0.42, -0.06, -3]} scale={[1.15, 1.15, 1.61]} />
            <mesh geometry={nodes.Circle065_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[0.3, 0.29, 0.86]} scale={[1.15, 1.15, 1.61]} />
            <mesh geometry={nodes.Circle066_Material004_0.geometry} material={materials['Material.004']} position={[-0.42, 0.11, 0.35]} rotation={[-0.22, 0.35, 2.15]} scale={[0.92, 0.92, 1.29]} />
            <mesh geometry={nodes.Circle067_Material004_0.geometry} material={materials['Material.004']} position={[-0.64, 0.44, 0.35]} rotation={[0.58, -0.05, -0.07]} scale={[0.92, 0.92, 1.29]} />
            <mesh geometry={nodes.Circle068_Material004_0.geometry} material={materials['Material.004']} position={[-0.71, 0.39, -0.37]} rotation={[0.37, -0.24, -0.68]} scale={[1.04, 1.04, 1.46]} />
            <mesh geometry={nodes.Circle070_Material004_0.geometry} material={materials['Material.004']} position={[-0.24, -0.96, 1.39]} rotation={[-0.53, -0.43, -2.51]} scale={[0.73, 0.73, 1.03]} />
          </group>
          <group position={[312.68, 730.03, -424.34]} rotation={[-2.64, -0.64, 1.94]} scale={83.35}>
            <mesh geometry={nodes.Plane021_Leaves_2_0.geometry} material={materials.Leaves_2} />
            <mesh geometry={nodes.Plane021_Leaves_1_0.geometry} material={materials.Leaves_1} />
          </group>
          <group position={[712.63, 81.11, -249.02]} rotation={[-1.95, -0.37, -1.25]} scale={52.17}>
            <mesh geometry={nodes.Plane013_Leaves_2_0.geometry} material={materials.Leaves_2} />
            <mesh geometry={nodes.Plane013_Leaves_3_0.geometry} material={materials.Leaves_3} />
          </group>
          <group position={[-9.49, 81.11, -1107.53]} rotation={[-0.89, -0.23, 1.25]} scale={52.17}>
            <mesh geometry={nodes.Plane012_Leaves_2_0.geometry} material={materials.Leaves_2} />
            <mesh geometry={nodes.Plane012_Leaves_3_0.geometry} material={materials.Leaves_3} />
          </group>
          <group position={[-715.9, 81.11, -318.85]} rotation={[-1.01, 1, 2.23]} scale={52.17}>
            <mesh geometry={nodes.Plane014_Leaves_2_0.geometry} material={materials.Leaves_2} />
            <mesh geometry={nodes.Plane014_Leaves_3_0.geometry} material={materials.Leaves_3} />
          </group>
          <group position={[-172.69, 290.31, -428.63]} rotation={[-0.99, -0.16, -0.94]} scale={[58.63, 58.48, 57.04]}>
            <mesh geometry={nodes.Plane018_Leaves_4_0.geometry} material={materials.Leaves_4} />
            <mesh geometry={nodes.Plane018_Leaves_1_0.geometry} material={materials.Leaves_1} />
          </group>
          <group position={[57.17, 97.03, 793.75]} rotation={[-Math.PI / 2, 0, 0.03]} scale={[102.93, 60.56, 78.04]}>
            <mesh geometry={nodes.Plane001_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Plane001_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-120.33, 149.05, 806.82]} rotation={[-Math.PI / 2, 0, 0]} scale={[67.68, 33.71, 138.85]}>
            <mesh geometry={nodes.Cube009_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Cube009_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[0, 41.92, 140.18]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 41.83, 47.72]}>
            <mesh geometry={nodes.Cube011_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Cube011_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[258.69, 116.56, -610.65]} rotation={[-Math.PI / 2, 0, 0.37]} scale={[61.99, 61.99, 73.43]}>
            <mesh geometry={nodes.Circle001_TT_checker_4_0.geometry} material={materials.TT_checker_4} />
            <mesh geometry={nodes.Circle001_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[0, -1.79, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube012_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube012_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[0, -0.95, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane_Line_art_Green__0.geometry} material={materials.Line_art_Green} />
          </group>
          <group position={[-249.68, 39.57, 652.35]} rotation={[-Math.PI / 2, 0, -0.53]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube014_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube014_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[407.55, 95.95, 362.89]} rotation={[-Math.PI / 2, 0, 1.3]} scale={[84.18, 63.5, 55.53]}>
            <mesh geometry={nodes.Cube015_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube015_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[342.24, 75.36, 646.89]} rotation={[-Math.PI / 2, 0, 0]} scale={[15.86, 15.86, 16.24]}>
            <mesh geometry={nodes.Circle002_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle002_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-333.34, 76.26, 679.3]} rotation={[-1.54, 0.02, 0]} scale={[15.86, 15.86, 16.24]}>
            <mesh geometry={nodes.Circle003_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle003_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-333.34, 76.26, 679.3]} rotation={[-1.54, 0.02, 0]} scale={[17.41, 17.41, 17.83]}>
            <mesh geometry={nodes.Circle004_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle004_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-26.67, 136.85, 772.18]} rotation={[-Math.PI / 2, 0, -2.24]} scale={116.55}>
            <mesh geometry={nodes.Circle006_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle006_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[342.22, 75.36, 646.89]} rotation={[-Math.PI / 2, 0, 0]} scale={[17.41, 17.41, 17.83]}>
            <mesh geometry={nodes.Circle005_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle005_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[148.73, 78.68, -70.84]} rotation={[-Math.PI / 2, 0, -1.91]} scale={166.21}>
            <mesh geometry={nodes.Circle007_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle007_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-165.03, 10.82, 727]} rotation={[-1.41, 0, 0]} scale={[49.6, 19.31, 100]}>
            <mesh geometry={nodes.Plane002_TT_checker_3_0.geometry} material={materials.TT_checker_3} />
            <mesh geometry={nodes.Plane002_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[36.05, 73.07, 702.08]} rotation={[-Math.PI / 2, 0, 0]} scale={25.87}>
            <mesh geometry={nodes.Circle008_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle008_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[276.81, 93.09, 724.28]} rotation={[-1.59, 0.02, 0.81]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube016_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube016_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[409.2, 11.73, 271.11]} rotation={[-Math.PI / 2, 0, 0]} scale={[21.16, 21.16, 21.67]}>
            <mesh geometry={nodes.Circle009_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle009_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-95.07, 163.13, 786.08]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={10.05}>
            <mesh geometry={nodes.Plane003_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane003_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-100.55, 223.36, 785.33]} rotation={[-Math.PI / 2, 0, 0.86]} scale={9.18}>
            <mesh geometry={nodes.Plane005_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane005_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-146.23, 223.31, 778.11]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={10.05}>
            <mesh geometry={nodes.Plane004_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane004_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-77.16, 223.36, 791.56]} rotation={[-Math.PI / 2, 0, 1.32]} scale={9.18}>
            <mesh geometry={nodes.Plane006_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane006_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[185.49, 44.89, 734.48]} rotation={[-1.16, 0.24, -2.91]} scale={208.57}>
            <mesh geometry={nodes.Plane007_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane007_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-5.97, 103.9, 820.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[15.86, 15.86, 16.24]}>
            <mesh geometry={nodes.Circle011_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle011_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-5.99, 103.9, 820.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[17.41, 17.41, 17.83]}>
            <mesh geometry={nodes.Circle012_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle012_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-95.77, 102.4, 790.37]} rotation={[-Math.PI / 2, 0, 0]} scale={[8.93, 8.93, 9.15]}>
            <mesh geometry={nodes.Circle013_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle013_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-96.2, 116.56, 790.82]} rotation={[-1.49, 0.07, -0.29]} scale={[8.93, 8.93, 9.15]}>
            <mesh geometry={nodes.Circle014_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle014_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[412.23, 96.51, 513.87]} rotation={[-1.58, 0, 1.48]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube017_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube017_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-266.64, 94.47, 737.59]} rotation={[-1.63, 0, 2.14]} scale={[84.18, 63.5, 55.53]}>
            <mesh geometry={nodes.Cube018_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube018_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-410.45, 96.21, 549.41]} rotation={[-1.58, 0.02, 1.81]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube019_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube019_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-363.09, 27.01, 204.94]} rotation={[-1.55, -0.03, 1.15]} scale={[84.18, 63.5, 55.53]}>
            <mesh geometry={nodes.Cube020_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube020_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-419.37, 103.61, 7.97]} rotation={[-Math.PI / 2, 0, -1.2]} scale={[71.65, 54.05, 47.27]}>
            <mesh geometry={nodes.Cube021_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube021_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[411.37, 3.75, 40.43]} rotation={[-1.6, -0.02, -0.34]} scale={[21.16, 21.16, 21.67]}>
            <mesh geometry={nodes.Circle015_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle015_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-145.9, 14.68, 149.18]} rotation={[-1.42, 0.09, -2.48]} scale={208.57}>
            <mesh geometry={nodes.Plane009_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane009_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-404.49, 24.75, 526.66]} rotation={[3.14, 0.01, 0.78]} scale={[15.86, 15.86, 16.24]}>
            <mesh geometry={nodes.Circle016_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle016_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-416.76, 93.84, 217.66]} rotation={[-1.56, 0, 1.57]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube022_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube022_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-269.91, 267.49, 533.6]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.17, 27.17, 27.82]}>
            <mesh geometry={nodes.Circle018_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle018_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-4.39, 426.47, 0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.17, 27.17, 27.82]}>
            <mesh geometry={nodes.Circle019_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle019_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[15.24, 396.85, -374.8]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.17, 27.17, 27.82]}>
            <mesh geometry={nodes.Circle020_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle020_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[676.82, 3.19, 186.89]} rotation={[-Math.PI / 2, 0, -0.19]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube023_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube023_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-422.3, 93.73, -197.55]} rotation={[-1.53, 0, 1.57]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube024_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube024_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-414.17, 76.57, -316.08]} rotation={[-1.54, 0.02, 0]} scale={[15.86, 15.86, 16.24]}>
            <mesh geometry={nodes.Circle021_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle021_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-414.17, 76.57, -316.08]} rotation={[-1.54, 0.02, 0]} scale={[17.41, 17.41, 17.83]}>
            <mesh geometry={nodes.Circle022_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle022_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-58.17, 95.94, -807.4]} rotation={[-1.57, -0.04, -0.07]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube025_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube025_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-112.72, 25.72, -782.23]} rotation={[-0.21, 0.72, -2.85]} scale={[21.16, 21.16, 21.67]}>
            <mesh geometry={nodes.Circle023_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle023_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-50.77, 60.91, -284.31]} rotation={[-1.49, 0.25, 1.77]} scale={[84.18, 63.5, 55.53]}>
            <mesh geometry={nodes.Cube026_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube026_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[-410.22, 94.01, -480.61]} rotation={[-1.54, -0.02, 1.36]} scale={[84.18, 63.5, 55.53]}>
            <mesh geometry={nodes.Cube027_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube027_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[135.16, -1.02, 162.95]} rotation={[-Math.PI / 2, 0, 1.16]} scale={[13.36, 13.36, 13.68]}>
            <mesh geometry={nodes.Circle024_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle024_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[133.7, 20.95, 162.75]} rotation={[-1.6, 0.11, 0.88]} scale={[13.36, 13.36, 13.68]}>
            <mesh geometry={nodes.Circle025_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle025_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[125.16, -1.39, 127.16]} rotation={[-Math.PI / 2, 0, 1.16]} scale={[13.36, 13.36, 13.68]}>
            <mesh geometry={nodes.Circle026_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle026_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[166.57, 13.41, 173.65]} rotation={[-0.19, 0.88, -0.9]} scale={[13.36, 13.36, 13.68]}>
            <mesh geometry={nodes.Circle027_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle027_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[414.2, 93.71, -463.9]} rotation={[-1.55, 0, -1.59]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube029_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube029_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[656.16, 3.19, 129.53]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube030_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube030_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[729.38, -2.43, 121.77]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube031_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube031_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[730.11, -2.43, 198.31]} rotation={[-Math.PI / 2, 0, 0.03]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube032_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube032_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[794.27, -4.11, 170.71]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube033_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube033_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[407.27, 94.24, -253.92]} rotation={[-1.53, 0.01, 1.79]} scale={[84.18, 63.5, 55.53]}>
            <mesh geometry={nodes.Cube034_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube034_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[412.05, 76.77, -104.35]} rotation={[-1.63, 0, 0]} scale={[15.86, 15.86, 16.24]}>
            <mesh geometry={nodes.Circle028_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle028_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[412.03, 76.77, -104.36]} rotation={[-1.63, 0, 0]} scale={[17.41, 17.41, 17.83]}>
            <mesh geometry={nodes.Circle029_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle029_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[611.99, 36.49, 443.98]} rotation={[-Math.PI / 2, 0, 0.39]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube035_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube035_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[636.25, 5.69, -572.82]} rotation={[-Math.PI / 2, 0, 1.88]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube036_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube036_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[639.87, 21.13, -47.06]} rotation={[-1.51, -0.16, 2.05]} scale={208.57}>
            <mesh geometry={nodes.Plane010_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Plane010_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[720.6, 1.37, 37.45]} rotation={[-Math.PI / 2, 0, 0.75]} scale={[22.63, 22.63, 23.16]}>
            <mesh geometry={nodes.Circle030_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Circle030_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-484.24, 10.86, 869.75]} rotation={[-Math.PI / 2, 0, -1.42]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube038_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube038_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[74.46, 28.6, -484.87]} rotation={[-1.56, 0.05, -1.06]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube039_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube039_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-229.35, 9.83, -344.75]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube046_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube046_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[222.85, 34.72, -46.29]} rotation={[-1.55, 0, 0.62]} scale={[77.66, 58.58, 51.23]}>
            <mesh geometry={nodes.Cube047_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube047_Line_art__Red_0.geometry} material={materials.Line_art__Red} />
          </group>
          <group position={[800.54, 0.48, -112.65]} rotation={[-1.68, 0.16, 0.27]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube048_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube048_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-683.53, 6.79, -672.67]} rotation={[-1.37, 0.17, 2.57]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube049_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube049_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[300.24, -8.24, -1.07]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cube013_TT_checker_1_0.geometry} material={materials.TT_checker_1} />
            <mesh geometry={nodes.Cube013_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[779.04, -6.09, 231.42]} rotation={[-1.52, 0, 1.09]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube010_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube010_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[871.62, -10.97, 101.42]} rotation={[-1.73, 0.26, -1.15]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube050_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube050_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[179.38, 6.27, 335.83]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[119.35, 119.35, 68.93]}>
            <mesh geometry={nodes.Cube051_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube051_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[175.28, 6.27, 401.36]} rotation={[-Math.PI / 2, 0, 0.07]} scale={[166.14, 119.65, 68.93]}>
            <mesh geometry={nodes.Cube052_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube052_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-180.42, 6.27, 233.24]} rotation={[-Math.PI / 2, 0, 0.73]} scale={[166.14, 119.65, 68.93]}>
            <mesh geometry={nodes.Cube053_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube053_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-186.35, 11.09, 305.63]} rotation={[-Math.PI / 2, 0, 2.97]} scale={[122.08, 111.17, 120.84]}>
            <mesh geometry={nodes.Cube054_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube054_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[112.1, 9.85, 533.97]} rotation={[-Math.PI / 2, 0, -0.41]} scale={[125.12, 147.46, 75.78]}>
            <mesh geometry={nodes.Cube055_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube055_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[164.32, 6.27, 495.2]} rotation={[-Math.PI / 2, 0, -1.69]} scale={[135.91, 123.25, 56.15]}>
            <mesh geometry={nodes.Cube056_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube056_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[194.94, 9.23, 451.76]} rotation={[-Math.PI / 2, 0, -0.8]} scale={[79.88, 79.88, 98.59]}>
            <mesh geometry={nodes.Cube057_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube057_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[192.59, 8.76, 237.53]} rotation={[-Math.PI / 2, 0, 3.07]} scale={[92.41, 92.41, 85.39]}>
            <mesh geometry={nodes.Cube058_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube058_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[164.83, 8.3, 279.5]} rotation={[-Math.PI / 2, 0, -0.12]} scale={[119.35, 119.35, 82.95]}>
            <mesh geometry={nodes.Cube059_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube059_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[62.31, 9.23, 521.27]} rotation={[-Math.PI / 2, 0, 0.77]} scale={[79.88, 79.88, 98.59]}>
            <mesh geometry={nodes.Cube060_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube060_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[18.35, 6.27, 544.9]} rotation={[-Math.PI / 2, 0, 2.37]} scale={[114.23, 103.59, 56.15]}>
            <mesh geometry={nodes.Cube061_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube061_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-36.91, 14.3, 533.44]} rotation={[-Math.PI / 2, 0, 0.74]} scale={[125.12, 147.46, 75.78]}>
            <mesh geometry={nodes.Cube062_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube062_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-117.17, 11.17, 209.87]} rotation={[-Math.PI / 2, 0, -1.13]} scale={[92.41, 92.41, 110.59]}>
            <mesh geometry={nodes.Cube063_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube063_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-180.31, 6.27, 370.41]} rotation={[-Math.PI / 2, 0, 0.88]} scale={[166.14, 119.65, 68.93]}>
            <mesh geometry={nodes.Cube064_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube064_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-160.64, 9.23, 420.8]} rotation={[-Math.PI / 2, 0, -0.8]} scale={[79.88, 79.88, 98.59]}>
            <mesh geometry={nodes.Cube065_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube065_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-160.19, 6.27, 517.91]} rotation={[-Math.PI / 2, 0, 2.36]} scale={[137.28, 98.86, 68.93]}>
            <mesh geometry={nodes.Cube066_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube066_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-184.75, 10.17, 467.07]} rotation={[-Math.PI / 2, 0, 2.37]} scale={[89.73, 81.37, 44.81]}>
            <mesh geometry={nodes.Cube067_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube067_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-96.08, 12.44, 514.98]} rotation={[-Math.PI / 2, 0, -0.8]} scale={[79.88, 79.88, 98.59]}>
            <mesh geometry={nodes.Cube068_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube068_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[-100.96, 11.53, 553.27]} rotation={[-1.63, 0.03, -3.04]} scale={[131.91, 73.62, 38.78]}>
            <mesh geometry={nodes.Cube069_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube069_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[849.91, -6.09, 445.82]} rotation={[-1.52, 0, 1.09]} scale={[100, 100, 57.76]}>
            <mesh geometry={nodes.Cube070_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube070_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <group position={[856.52, -17.38, 387]} rotation={[-1.71, -0.13, 1.97]} scale={[81.93, 81.93, 47.32]}>
            <mesh geometry={nodes.Cube071_TT_checker_2_0.geometry} material={materials.TT_checker_2} />
            <mesh geometry={nodes.Cube071_Line_art_0.geometry} material={materials.Line_art} />
          </group>
          <mesh geometry={nodes.Cube042_Glass_0.geometry} material={materials.Glass} position={[0, 76.81, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[494.26, 895.57, 265.09]} />
          <mesh geometry={nodes.Plane015_Grass_0.geometry} material={materials.Grass} position={[618.21, 16.97, 560.45]} rotation={[-1.89, 0.01, -1.01]} scale={60.04} />
          <mesh geometry={nodes.Plane016_Grass_0.geometry} material={materials.Grass} position={[640.31, 9.47, 516.81]} rotation={[-Math.PI / 2, 0, 0.03]} scale={58.17} />
          <mesh geometry={nodes.Plane017_Grass_0.geometry} material={materials.Grass} position={[721.02, 7.97, 322.71]} rotation={[-1.73, -0.03, 0.98]} scale={58.17} />
          <mesh geometry={nodes.Plane019_Grass_0.geometry} material={materials.Grass} position={[756.07, 11.66, -11.3]} rotation={[-1.76, -0.44, 0.41]} scale={[58.17, 58.17, 50.72]} />
          <mesh geometry={nodes.Plane020_Grass_0.geometry} material={materials.Grass} position={[641.83, -1.01, -86.88]} rotation={[-1.69, -0.38, 2.37]} scale={[58.17, 58.17, 56.83]} />
          <mesh geometry={nodes.Plane022_Grass_0.geometry} material={materials.Grass} position={[799.65, -7.43, 14.8]} rotation={[-Math.PI / 2, 0, -0.34]} scale={[54.47, 54.47, 47.49]} />
          <mesh geometry={nodes.Plane023_Grass_0.geometry} material={materials.Grass} position={[821.4, 2.9, 53.51]} rotation={[-1.85, -0.05, -1.36]} scale={[54.47, 54.47, 47.49]} />
          <mesh geometry={nodes.Plane024_Grass_0.geometry} material={materials.Grass} position={[693.57, 13.19, -604.74]} rotation={[-1.81, -0.29, -1.1]} scale={[55.32, 54.61, 52.72]} />
          <mesh geometry={nodes.Plane025_Grass_0.geometry} material={materials.Grass} position={[766.04, 2.79, -534.99]} rotation={[-2.11, 0.02, -1.94]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane026_Grass_0.geometry} material={materials.Grass} position={[420.69, 13.19, -815.47]} rotation={[-1.64, -0.09, -0.63]} scale={[55.32, 54.61, 52.72]} />
          <mesh geometry={nodes.Plane027_Grass_0.geometry} material={materials.Grass} position={[483.47, 2.79, -761.7]} rotation={[-1.89, -0.3, -1.95]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane028_Grass_0.geometry} material={materials.Grass} position={[367.52, 31.83, -848.84]} rotation={[-1.53, -0.06, -0.92]} scale={[55.32, 54.61, 52.72]} />
          <mesh geometry={nodes.Plane029_Grass_0.geometry} material={materials.Grass} position={[477.93, 2.79, -729.23]} rotation={[-1.49, -0.38, -2.59]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane030_Grass_0.geometry} material={materials.Grass} position={[485.49, -0.02, -824.75]} rotation={[-1.49, -0.46, 2.84]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane031_Grass_0.geometry} material={materials.Grass} position={[747.81, -0.02, -602.45]} rotation={[-1.49, -0.46, 2.84]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane032_Grass_0.geometry} material={materials.Grass} position={[546.72, 13.19, -459.18]} rotation={[-1.95, -0.04, -1.86]} scale={[55.32, 54.61, 52.72]} />
          <mesh geometry={nodes.Plane033_Grass_0.geometry} material={materials.Grass} position={[552.15, 2.79, -376.69]} rotation={[-2, 0.01, -2.69]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane034_Grass_0.geometry} material={materials.Grass} position={[109.07, 13.19, -1149.11]} rotation={[-2.01, -0.02, -1.16]} scale={[55.32, 54.61, 52.72]} />
          <mesh geometry={nodes.Plane035_Grass_0.geometry} material={materials.Grass} position={[224.52, 2.79, -1089.22]} rotation={[-2.02, -0.1, -2.01]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane036_Grass_0.geometry} material={materials.Grass} position={[198.2, 7.32, -1154.17]} rotation={[-1.81, -0.11, 2.93]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane037_Grass_0.geometry} material={materials.Grass} position={[-733.59, 13.19, -754.47]} rotation={[-1.58, -0.54, -0.92]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane038_Grass_0.geometry} material={materials.Grass} position={[-597.47, 10.59, -707.38]} rotation={[-1.8, -0.3, -0.35]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane039_Grass_0.geometry} material={materials.Grass} position={[-644.46, 7.32, -759.52]} rotation={[-1.84, -0.5, 2.55]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane040_Grass_0.geometry} material={materials.Grass} position={[-580.21, 27.61, -781.81]} rotation={[-1.83, -0.3, -0.58]} scale={[51.41, 50.75, 48.99]} />
          <mesh geometry={nodes.Plane041_Grass_0.geometry} material={materials.Grass} position={[-569.15, 27.61, -613.5]} rotation={[-1.47, -0.02, -0.6]} scale={[51.41, 50.75, 48.99]} />
          <mesh geometry={nodes.Plane042_Grass_0.geometry} material={materials.Grass} position={[-770.93, 14.48, -108.8]} rotation={[-1.82, -0.43, -1.07]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane044_Grass_0.geometry} material={materials.Grass} position={[-682.71, -0.75, -32.9]} rotation={[-1.89, -0.04, -0.47]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane045_Grass_0.geometry} material={materials.Grass} position={[-661.01, 1.47, -78.59]} rotation={[-2.06, -0.37, 2.43]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane046_Grass_0.geometry} material={materials.Grass} position={[-763.5, 7.76, -201.63]} rotation={[-1.56, 0.06, -1.21]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane047_Grass_0.geometry} material={materials.Grass} position={[-532.72, 10.09, 663.01]} rotation={[-2.02, -0.05, -0.73]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane048_Grass_0.geometry} material={materials.Grass} position={[-569.81, 7.76, 496.76]} rotation={[-1.55, 0.06, -1.5]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane049_Grass_0.geometry} material={materials.Grass} position={[-558.05, -18.15, 796.55]} rotation={[-1.6, -0.1, 0]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane050_Grass_0.geometry} material={materials.Grass} position={[-384.82, 14.48, 871.59]} rotation={[-1.97, 0.11, -0.62]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane051_Grass_0.geometry} material={materials.Grass} position={[-472.99, -11.85, 949.8]} rotation={[-1.68, -0.17, 0.07]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane052_Grass_0.geometry} material={materials.Grass} position={[227.6, 14.48, 1097.05]} rotation={[-1.68, -0.46, -0.67]} scale={[60.45, 59.67, 57.61]} />
          <mesh geometry={nodes.Plane053_Grass_0.geometry} material={materials.Grass} position={[203.11, 2.64, 1135.98]} rotation={[-1.68, -0.17, 0.07]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane054_Grass_0.geometry} material={materials.Grass} position={[-57.46, 14.48, 969.31]} rotation={[-1.68, -0.46, -0.67]} scale={[56.63, 55.9, 53.97]} />
          <mesh geometry={nodes.Plane055_Grass_0.geometry} material={materials.Grass} position={[-141.96, 11.31, 975.98]} rotation={[-1.68, -0.17, 0.07]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane056_Grass_0.geometry} material={materials.Grass} position={[-195.6, 2.64, 1140.33]} rotation={[-1.68, -0.17, 0.07]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane057_Grass_0.geometry} material={materials.Grass} position={[-286.16, -0.1, 1047.07]} rotation={[-1.68, -0.17, 0.07]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane058_Grass_0.geometry} material={materials.Grass} position={[-36.11, 26.82, 379.97]} rotation={[-1.52, 0.1, -1.43]} scale={[55.32, 54.61, 52.72]} />
          <mesh geometry={nodes.Plane059_Grass_0.geometry} material={materials.Grass} position={[58.72, 16.04, 466.18]} rotation={[-1.76, -0.08, -2.02]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane060_Grass_0.geometry} material={materials.Grass} position={[22.74, 16.49, 347.01]} rotation={[-1.56, -0.08, 2.85]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane061_Grass_0.geometry} material={materials.Grass} position={[-38.79, 16.49, 271.13]} rotation={[-1.61, 0.11, -2.97]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane062_Grass_0.geometry} material={materials.Grass} position={[-28.56, 14.36, 317.09]} rotation={[-1.61, 0.11, -2.97]} scale={[38.21, 37.71, 36.41]} />
          <mesh geometry={nodes.Plane063_Grass_0.geometry} material={materials.Grass} position={[118.07, 14.36, 229]} rotation={[-1.61, 0.11, -2.97]} scale={[38.21, 37.71, 36.41]} />
          <mesh geometry={nodes.Plane064_Grass_0.geometry} material={materials.Grass} position={[42.23, 10.6, -768.52]} rotation={[-1.69, -0.01, -1.68]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane065_Grass_0.geometry} material={materials.Grass} position={[-101.19, 22.94, -697.59]} rotation={[-1.61, -0.05, 2.77]} scale={[45.29, 44.71, 43.16]} />
          <mesh geometry={nodes.Plane066_Grass_0.geometry} material={materials.Grass} position={[-126.77, 16.49, 280.21]} rotation={[-1.69, 0.03, -2.03]} scale={[36.28, 35.81, 34.57]} />
          <mesh geometry={nodes.Plane067_Grass_0.geometry} material={materials.Grass} position={[24.84, 6.44, 230.56]} rotation={[-1.65, 0.11, 2.85]} scale={[36.28, 35.81, 34.57]} />
          <mesh geometry={nodes.Plane068_Grass_0.geometry} material={materials.Grass} position={[-159.14, 16.49, 332.07]} rotation={[-1.69, -0.16, -2.6]} scale={[29.38, 29.01, 28]} />
          <mesh geometry={nodes.Plane069_Grass_0.geometry} material={materials.Grass} position={[68.1, 14.36, 398.05]} rotation={[-1.52, 0.12, -2.56]} scale={[38.21, 37.71, 36.41]} />
          <mesh geometry={nodes.Plane070_Grass_0.geometry} material={materials.Grass} position={[0.59, 16.04, 489.18]} rotation={[-1.34, 0.12, -1.97]} scale={[47.63, 47.02, 45.39]} />
          <mesh geometry={nodes.Plane071_Grass_0.geometry} material={materials.Grass} position={[16.58, 14.36, 451.35]} rotation={[-1.52, 0.12, -2.56]} scale={[38.21, 37.71, 36.41]} />
          <mesh geometry={nodes.Plane072_Grass_0.geometry} material={materials.Grass} position={[253.2, 14.36, 734.98]} rotation={[-1.61, 0.11, -2.97]} scale={[38.21, 37.71, 36.41]} />
          <mesh geometry={nodes.Plane073_Grass_0.geometry} material={materials.Grass} position={[279.38, 16.04, 686.26]} rotation={[-2.06, -0.15, -1.74]} scale={[32.66, 32.24, 31.12]} />
          <mesh geometry={nodes.Plane074_Grass_0.geometry} material={materials.Grass} position={[390.15, 16.04, 528.55]} rotation={[-1.66, 0.27, -2.12]} scale={[32.66, 32.24, 31.12]} />
          <mesh geometry={nodes.Plane075_Grass_0.geometry} material={materials.Grass} position={[414.74, 16.04, 508.88]} rotation={[-1.66, -0.13, -1.65]} scale={[32.66, 32.24, 31.12]} />
          <mesh geometry={nodes.Plane076_Grass_0.geometry} material={materials.Grass} position={[397.57, 16.04, 376.83]} rotation={[-1.53, 0.31, -0.61]} scale={[28.61, 28.24, 27.27]} />
          <mesh geometry={nodes.Plane077_Grass_0.geometry} material={materials.Grass} position={[436.44, 16.04, 241.19]} rotation={[-1.48, 0.3, -0.8]} scale={[28.61, 28.24, 27.27]} />
          <mesh geometry={nodes.Plane078_Grass_0.geometry} material={materials.Grass} position={[397.05, 16.04, 80.03]} rotation={[-1.48, 0.3, -0.8]} scale={[26.54, 26.19, 25.29]} />
          <mesh geometry={nodes.Plane079_Grass_0.geometry} material={materials.Grass} position={[389.57, 16.04, 2.39]} rotation={[-1.84, -0.2, -0.88]} scale={[26.54, 26.19, 25.29]} />
          <mesh geometry={nodes.Plane080_Grass_0.geometry} material={materials.Grass} position={[-408.82, 16.49, 350.06]} rotation={[-1.92, -0.04, 2.66]} scale={[36.4, 35.93, 34.68]} />
          <mesh geometry={nodes.Plane081_Grass_0.geometry} material={materials.Grass} position={[-421.14, 6.7, 430.3]} rotation={[-1.3, -0.1, 2.78]} scale={[38.21, 37.71, 36.41]} />
          <mesh geometry={nodes.Plane082_Grass_0.geometry} material={materials.Grass} position={[-408.46, 16.49, 22.9]} rotation={[-1.3, 0.22, 1.41]} scale={[36.4, 35.93, 34.68]} />
          <mesh geometry={nodes.Plane083_Grass_0.geometry} material={materials.Grass} position={[-404, 16.49, -98.97]} rotation={[-1.83, 0.23, 2.28]} scale={[36.4, 35.93, 34.68]} />
          <mesh geometry={nodes.Plane084_Grass_0.geometry} material={materials.Grass} position={[402.54, 16.49, -226.57]} rotation={[-1.83, 0.23, 2.28]} scale={[36.4, 35.93, 34.68]} />
          <mesh geometry={nodes.Plane085_Grass_0.geometry} material={materials.Grass} position={[398.07, 16.49, -492.17]} rotation={[-1.83, 0.23, 2.28]} scale={[36.4, 35.93, 34.68]} />
          <mesh geometry={nodes.Plane086_Grass_0.geometry} material={materials.Grass} position={[862.32, -6.13, 530.19]} rotation={[-2.06, -0.3, -1.38]} scale={60.04} />
          <mesh geometry={nodes.Plane087_Grass_0.geometry} material={materials.Grass} position={[904.22, -9.38, 418.91]} rotation={[-2.09, -0.09, 0.21]} scale={58.17} />
          <mesh geometry={nodes.Plane088_Grass_0.geometry} material={materials.Grass} position={[775.05, 7.97, 503.31]} rotation={[-2.19, 0, 0.66]} scale={58.17} />
          <mesh geometry={nodes.Circle017_Material028_0.geometry} material={materials.TT_checker_4} position={[341.97, 113.49, 646.95]} rotation={[-Math.PI / 2, 0, 0.32]} scale={30.82} />
          <mesh geometry={nodes.Circle071_Material028_0.geometry} material={materials.TT_checker_4} position={[-7.04, 153.13, 818.92]} rotation={[-Math.PI / 2, 0, -0.56]} scale={30.82} />
          <mesh geometry={nodes.Plane089_Grass_0.geometry} material={materials.Grass} position={[411.76, 112.39, 529.37]} rotation={[-1.73, -0.04, 1.06]} scale={[26.21, 16.85, 33.58]} />
          <mesh geometry={nodes.Plane090_Grass_0.geometry} material={materials.Grass} position={[414.4, 112.39, 497.54]} rotation={[-1.73, -0.04, 1.06]} scale={[26.21, 16.85, 33.58]} />
          <mesh geometry={nodes.Plane091_Leaves_4_0.geometry} material={materials.Leaves_4} position={[410.1, 73.23, 39.28]} rotation={[-1.53, -0.78, 0.31]} scale={31.57} />
          <mesh geometry={nodes.Plane092_Leaves_4_0.geometry} material={materials.Leaves_4} position={[403.58, 91.02, 31.67]} rotation={[-2.98, -0.06, -1.48]} scale={31.57} />
          <mesh geometry={nodes.Plane093_Leaves_4_0.geometry} material={materials.Leaves_4} position={[398.5, 91.02, 55.64]} rotation={[2.87, 0.67, -0.65]} scale={31.57} />
          <mesh geometry={nodes.Plane094_Grass_0.geometry} material={materials.Grass} position={[408.28, 57.79, 40.03]} rotation={[-1.48, 0.3, -0.8]} scale={[26.54, 26.19, 25.29]} />
          <mesh geometry={nodes.Plane095_Leaves_4_0.geometry} material={materials.Leaves_4} position={[421.47, 73.23, 281.46]} rotation={[-1.53, -0.78, 0.31]} scale={31.57} />
          <mesh geometry={nodes.Plane096_Leaves_2_0.geometry} material={materials.Leaves_2} position={[424.58, 67.13, 283.77]} rotation={[-Math.PI / 2, 0, 0]} scale={33.55} />
          <mesh geometry={nodes.Plane097_Leaves_2_0.geometry} material={materials.Leaves_2} position={[412.65, 67.13, 37.61]} rotation={[-Math.PI / 2, 0, 0]} scale={34.3} />
          <mesh geometry={nodes.Plane098_Leaves_4_0.geometry} material={materials.Leaves_4} position={[414.2, 86.29, 268.3]} rotation={[-1.53, -0.78, 0.31]} scale={31.57} />
          <mesh geometry={nodes.Plane099_Leaves_4_0.geometry} material={materials.Leaves_4} position={[113.83, 14.12, 408.46]} rotation={[0.16, 0.06, 1.48]} scale={[-32.84, 32.84, 32.84]} />
          <mesh geometry={nodes.Plane100_Leaves_4_0.geometry} material={materials.Leaves_4} position={[115.11, 14.12, 432.21]} rotation={[-0.43, 0.39, 1.32]} scale={[-32.84, 32.84, 32.84]} />
          <mesh geometry={nodes.Plane101_Leaves_4_0.geometry} material={materials.Leaves_4} position={[95.7, 34.53, 430.78]} rotation={[0.16, 0.06, 1.48]} scale={[-43.73, 43.73, 43.73]} />
          <mesh geometry={nodes.Plane102_Leaves_2_0.geometry} material={materials.Leaves_2} position={[104.68, 31.28, 435.02]} rotation={[-1.14, -0.04, -0.81]} scale={29.19} />
          <mesh geometry={nodes.Plane103_Leaves_2_0.geometry} material={materials.Leaves_2} position={[104.2, 31.28, 423.02]} rotation={[-1.77, -0.3, -0.13]} scale={29.19} />
          <mesh geometry={nodes.Plane104_Leaves_4_0.geometry} material={materials.Leaves_4} position={[116.63, 47.76, 450.73]} rotation={[0.16, 0.06, 1.48]} scale={[-39.01, 39.01, 39.01]} />
          <mesh geometry={nodes.Plane105_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-106.86, 19.97, 245.35]} rotation={[0.38, 1.34, 1.25]} scale={[-33.92, 33.92, 33.92]} />
          <mesh geometry={nodes.Plane106_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-124.87, 44.71, 246.86]} rotation={[0.38, 1.34, 1.25]} scale={[-30.27, 30.27, 30.27]} />
          <mesh geometry={nodes.Plane108_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-74.96, 32.33, 227.71]} rotation={[0.26, 0.17, 0.91]} scale={[-35.83, 35.83, 35.83]} />
          <mesh geometry={nodes.Plane109_Leaves_1_0.geometry} material={materials.Leaves_1} position={[-93.64, 36.34, 239.3]} rotation={[-1.61, 0.53, -0.25]} scale={31.33} />
          <mesh geometry={nodes.Plane110_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-274.68, 331.55, 534.89]} rotation={[-1.53, -0.78, 0.31]} scale={40.94} />
          <mesh geometry={nodes.Plane111_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-271.53, 346.86, 514.71]} rotation={[-1.09, -1.11, -0.12]} scale={36.17} />
          <mesh geometry={nodes.Plane107_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-272.54, 325.99, 491.61]} rotation={[-1.09, -1.11, -0.12]} scale={29.52} />
          <mesh geometry={nodes.Plane112_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-285.42, 278.44, 477.45]} rotation={[-2.09, -1.06, -1.21]} scale={34.82} />
          <mesh geometry={nodes.Plane113_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-277.55, 300.34, 486.25]} rotation={[-1.09, -1.11, -0.12]} scale={37.3} />
          <mesh geometry={nodes.Plane114_Leaves_4_0.geometry} material={materials.Leaves_4} position={[-272.22, 252.59, 480.83]} rotation={[-2.15, -0.66, -1.23]} scale={26.08} />
          <mesh geometry={nodes.Plane115_Leaves_4_0.geometry} material={materials.Leaves_4} position={[16.05, 470.42, -372.65]} rotation={[-1.46, -1.05, 0.23]} scale={40.94} />
          <mesh geometry={nodes.Plane116_Leaves_4_0.geometry} material={materials.Leaves_4} position={[15.99, 488.78, -390.39]} rotation={[-0.58, -1.36, 0.26]} scale={36.17} />
          <mesh geometry={nodes.Plane117_Leaves_4_0.geometry} material={materials.Leaves_4} position={[21.76, 471.92, -415.94]} rotation={[-0.58, -1.36, 0.26]} scale={29.52} />
          <mesh geometry={nodes.Plane118_Leaves_4_0.geometry} material={materials.Leaves_4} position={[35.56, 425.22, -432.55]} rotation={[-2.45, -1.22, -1.75]} scale={34.82} />
          <mesh geometry={nodes.Plane119_Leaves_4_0.geometry} material={materials.Leaves_4} position={[24.07, 446.9, -424.91]} rotation={[-0.58, -1.36, 0.26]} scale={37.3} />
          <mesh geometry={nodes.Plane120_Leaves_4_0.geometry} material={materials.Leaves_4} position={[20.63, 470.42, -352.49]} rotation={[-1.46, -1.05, 0.23]} scale={39.3} />
          <mesh geometry={nodes.Plane011_Leaves__drop_0.geometry} material={materials.Leaves__drop} position={[609.74, 453.52, -540.58]} rotation={[Math.PI, -1.37, Math.PI]} scale={100} />
          <mesh geometry={nodes.Plane043_Leaves__drop_0.geometry} material={materials.Leaves__drop} position={[622.3, 455.78, -552.09]} rotation={[0.25, -0.7, 1.92]} scale={100} />
          <mesh geometry={nodes.Plane121_Leaves__drop_0.geometry} material={materials.Leaves__drop} position={[397.52, 315.07, -821.54]} rotation={[Math.PI, -1.48, Math.PI]} scale={100} />
          <mesh geometry={nodes.Plane122_Leaves__drop_0.geometry} material={materials.Leaves__drop} position={[410.08, 457.14, -833.05]} rotation={[0.19, -0.04, 1.77]} scale={100} />
          <mesh geometry={nodes.Plane123_Leaves__drop_0.geometry} material={materials.Leaves__drop} position={[326.36, 380.25, -446.8]} rotation={[Math.PI, 0.6, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Plane124_Glow_0.geometry} material={materials.Glow} position={[387.31, 245.55, 361.84]} scale={37.99} />
          <mesh geometry={nodes.Plane127_Glow_0.geometry} material={materials.Glow} position={[381.5, 245.55, 392.81]} rotation={[0, -0.24, Math.PI]} scale={[-37.15, 37.15, 37.15]} />
          <mesh geometry={nodes.Plane125_Glow_0.geometry} material={materials.Glow} position={[48.53, 273.53, 684.97]} rotation={[0, -0.54, 0]} scale={37.99} />
          <mesh geometry={nodes.Plane126_Glow_0.geometry} material={materials.Glow} position={[27.58, 273.53, 708.51]} rotation={[0, -0.78, Math.PI]} scale={[-37.15, 37.15, 37.15]} />
          <mesh geometry={nodes.Plane128_Glow_0.geometry} material={materials.Glow} position={[-326.49, 273.84, 546.48]} rotation={[0, -1.03, 0]} scale={37.99} />
          <mesh geometry={nodes.Plane129_Glow_0.geometry} material={materials.Glow} position={[-356.07, 273.84, 557.31]} rotation={[0, -1.27, Math.PI]} scale={[-37.15, 37.15, 37.15]} />
          <mesh geometry={nodes.Plane130_Glow_0.geometry} material={materials.Glow} position={[141.55, 264.48, -706.85]} rotation={[0, -0.31, 0]} scale={37.99} />
          <mesh geometry={nodes.Plane131_Glow_0.geometry} material={materials.Glow} position={[126.44, 264.48, -679.2]} rotation={[0, -0.55, Math.PI]} scale={[-37.15, 37.15, 37.15]} />
          <mesh geometry={nodes.Cube040_TT_checker_2_0.geometry} material={materials.TT_checker_2} position={[192.9, 4.31, -431.34]} rotation={[-Math.PI / 2, 0, 1.09]} scale={[127.27, 127.27, 73.51]} />
          <mesh geometry={nodes.Cube041_TT_checker_2_0.geometry} material={materials.TT_checker_2} position={[-31.29, 4.31, -412.53]} rotation={[-Math.PI / 2, 0, -0.3]} scale={[127.27, 127.27, 73.51]} />
          <mesh geometry={nodes.Cube043_TT_checker_2_0.geometry} material={materials.TT_checker_2} position={[-71.51, 11.85, -197.1]} rotation={[-Math.PI / 2, 0, -0.3]} scale={[127.27, 127.27, 73.51]} />
          <mesh geometry={nodes.Cube044_TT_checker_2_0.geometry} material={materials.TT_checker_2} position={[-35.06, 6.82, -109.28]} rotation={[-1.56, 0.19, -2.59]} scale={[127.27, 127.27, 73.51]} />
          <mesh geometry={nodes.Cube045_TT_checker_2_0.geometry} material={materials.TT_checker_2} position={[143.33, 4.31, -260.12]} rotation={[-Math.PI / 2, 0, -2.42]} scale={[127.27, 127.27, 73.51]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/island-transformed.glb')
