/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 king.gltf --transform
Author: Pierre-Antoine (https://sketchfab.com/pa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-king-2eb21daf408141d1b2df1d91426935ad
Title: Mountain King
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/king-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.1, -1.09, -0.09]} rotation={[-1.45, 0.07, -0.01]} scale={1.19}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.mk3003} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.mk3003} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.mk30031} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.mk30031} />
      </group>
    </group>
  )
}

useGLTF.preload('/king-transformed.glb')
